import { Hono } from 'hono';
import type { Env } from '../types/env.js';
import { getBySpunId, linkMovieboxId } from '../identity/resolver.js';
import { errorResponse } from '../normalizer.js';
import { createSubtitleProxyToken } from '../proxy-token.js';
import type { MediaTitleRow } from '../types/index.js';
const download=new Hono<{Bindings:Env}>();
function qs(row:MediaTitleRow,type:string,extra:Record<string,string|undefined>):URLSearchParams{const p=new URLSearchParams({spun_id:row.spun_id,type,title:row.title});for(const[k,v]of Object.entries(extra))if(v)p.set(k,v);if(row.year!=null)p.set('year',String(row.year));if(row.tmdb_id!=null)p.set('tmdb_id',String(row.tmdb_id));if(row.anilist_id!=null)p.set('anilist_id',String(row.anilist_id));if(row.mal_id!=null)p.set('mal_id',String(row.mal_id));if(row.moviebox_id!=null)p.set('moviebox_id',String(row.moviebox_id));return p;}
async function handle(c:any,type:string,id:string,extra:Record<string,string|undefined>):Promise<Response>{const row=await getBySpunId(c.env,id);if(!row)return errorResponse('INVALID_ID','Content not found.',404);if(row.content_type!==type)return errorResponse('BAD_REQUEST','Content type mismatch.',400);if(!c.env.RENDER_BACKEND_URL)return errorResponse('SERVICE_OFFLINE','Download service is not configured yet.',503);try{const r=await fetch(`${c.env.RENDER_BACKEND_URL.replace(/\/$/,'')}/download?${qs(row,type,extra)}`,{headers:{'X-Spun-Secret':c.env.X_SPUN_SECRET,Accept:'application/json'},signal:AbortSignal.timeout(28_000)});const raw:any=await r.json();if(!r.ok)return new Response(JSON.stringify(raw),{status:r.status,headers:{'Content-Type':'application/json'}});const mapped=String(raw?.mapping?.moviebox_id??'');if(/^\d+$/.test(mapped)&&row.moviebox_id==null)await linkMovieboxId(c.env,row.spun_id,mapped).catch(()=>{});const mapItem=(x:any)=>({quality:x.quality,format:x.format,audio:x.audio??'Original',url:x.url,filename:x.filename??null,size:x.size??null});const downloads=Array.isArray(raw.downloads)?raw.downloads.map((x:any)=>Array.isArray(x?.options)?{season:Number(x.season),episode:Number(x.episode),options:x.options.map(mapItem)}:mapItem(x)):[];const origin=new URL(c.req.url).origin;const subtitles=await Promise.all((Array.isArray(raw.subtitles)?raw.subtitles:[]).map(async(x:any)=>{if(!x?.url)return null;const created=await createSubtitleProxyToken(c.env.SUBTITLE_PROXY_TOKEN_SECRET,x.url,String(x.language_code??'und'),{format:'srt',disposition:'attachment'});return {url:`${origin}/v1/proxy/subtitles?t=${encodeURIComponent(created.token)}`,language:String(x.language??'Unknown'),language_code:String(x.language_code??'und'),format:'srt'};}));return new Response(JSON.stringify({spun_id:row.spun_id,title:row.title,type,downloads,subtitles:subtitles.filter(Boolean)}),{status:200,headers:{'Content-Type':'application/json'}});}catch{return errorResponse('SERVICE_OFFLINE','Download service unavailable.',503);}}
download.get('/:type/:spunId/:season/:episode',(c)=>handle(c,c.req.param('type'),c.req.param('spunId'),{season:c.req.param('season'),episode:c.req.param('episode'),quality:c.req.query('quality')}));download.get('/:type/:spunId/:episode',async(c)=>{if(c.req.param('type')!=='anime')return errorResponse('BAD_REQUEST','Content type mismatch.',400);return handle(c,'anime',c.req.param('spunId'),{season:'1',episode:c.req.param('episode'),quality:c.req.query('quality')});});download.get('/:type/:spunId',(c)=>handle(c,c.req.param('type'),c.req.param('spunId'),{season:c.req.query('season'),episode:c.req.query('episode'),quality:c.req.query('quality')}));download.get('/:spunId',async(c)=>{const row=await getBySpunId(c.env,c.req.param('spunId'));if(!row)return errorResponse('INVALID_ID','Content not found.',404);return handle(c,row.content_type,c.req.param('spunId'),{season:c.req.query('season'),episode:c.req.query('episode'),quality:c.req.query('quality')});});export default download;
