import { Hono } from 'hono';
import type { Env } from '../types/env.js';
import { getBySpunId, linkMovieboxId } from '../identity/resolver.js';
import { errorResponse } from '../normalizer.js';
import { createStreamProxyToken } from '../proxy-token.js';
import type { MediaTitleRow } from '../types/index.js';
const stream = new Hono<{ Bindings: Env }>();
function params(row: MediaTitleRow, type: string, extra: Record<string,string|undefined>): URLSearchParams { const p=new URLSearchParams({spun_id:row.spun_id,type,title:row.title}); for(const [k,v] of Object.entries(extra))if(v)p.set(k,v); if(row.year!=null)p.set('year',String(row.year)); if(row.tmdb_id!=null)p.set('tmdb_id',String(row.tmdb_id)); if(row.anilist_id!=null)p.set('anilist_id',String(row.anilist_id)); if(row.mal_id!=null)p.set('mal_id',String(row.mal_id)); if(row.moviebox_id!=null)p.set('moviebox_id',String(row.moviebox_id)); return p; }
async function handle(c:any,type:string,id:string,extra:Record<string,string|undefined>):Promise<Response>{ const row=await getBySpunId(c.env,id); if(!row)return errorResponse('INVALID_ID','Content not found.',404); if(row.content_type!==type)return errorResponse('BAD_REQUEST','Content type mismatch.',400); if(!c.env.RENDER_BACKEND_URL)return errorResponse('SERVICE_OFFLINE','Stream service is not configured yet.',503); try{const r=await fetch(`${c.env.RENDER_BACKEND_URL.replace(/\/$/,'')}/stream?${params(row,type,extra)}`,{headers:{'X-Spun-Secret':c.env.X_SPUN_SECRET,Accept:'application/json'},signal:AbortSignal.timeout(28_000)}); const raw:any=await r.json(); if(!r.ok)return new Response(JSON.stringify(raw),{status:r.status,headers:{'Content-Type':'application/json'}}); const mapped=Number(raw?.mapping?.moviebox_id); if(Number.isSafeInteger(mapped)&&mapped>0&&row.moviebox_id==null)await linkMovieboxId(c.env,row.spun_id,mapped).catch(()=>{}); const subtitles=Array.isArray(raw.subtitles)?raw.subtitles:[]; const streams=await Promise.all((Array.isArray(raw.streams)?raw.streams:[]).map(async(x:any)=>{const u=String(x.url??'');const f=String(x.format??'').toLowerCase();if((f==='hls'||u.toLowerCase().includes('.m3u8'))&&u){const t=await createStreamProxyToken(c.env.STREAM_PROXY_TOKEN_SECRET||c.env.SUBTITLE_PROXY_TOKEN_SECRET,u,x.headers??{});return {quality:x.quality,format:'hls',audio:x.audio??'Original',url:`/v1/proxy/stream?t=${encodeURIComponent(t.token)}`};}return {quality:x.quality,format:x.format,audio:x.audio??'Original',url:u};})); return new Response(JSON.stringify({spun_id:row.spun_id,title:row.title,type,streams,subtitles}),{status:200,headers:{'Content-Type':'application/json'}});}catch{return errorResponse('SERVICE_OFFLINE','Stream service unavailable.',503);} }
stream.get('/:type/:spunId/:season/:episode',(c)=>handle(c,c.req.param('type'),c.req.param('spunId'),{season:c.req.param('season'),episode:c.req.param('episode'),quality:c.req.query('quality'),audio:c.req.query('audio')}));
stream.get('/:type/:spunId/:episode',async(c)=>{if(c.req.param('type')!=='anime')return errorResponse('BAD_REQUEST','Content type mismatch.',400);return handle(c,'anime',c.req.param('spunId'),{season:'1',episode:c.req.param('episode'),quality:c.req.query('quality'),audio:c.req.query('audio')});});
stream.get('/:type/:spunId',(c)=>handle(c,c.req.param('type'),c.req.param('spunId'),{season:c.req.query('season'),episode:c.req.query('episode'),quality:c.req.query('quality'),audio:c.req.query('audio')}));
stream.get('/:spunId',async(c)=>{const row=await getBySpunId(c.env,c.req.param('spunId'));if(!row)return errorResponse('INVALID_ID','Content not found.',404);return handle(c,row.content_type,c.req.param('spunId'),{season:c.req.query('season'),episode:c.req.query('episode'),quality:c.req.query('quality'),audio:c.req.query('audio')});});
export default stream;
