// metadata/src/config/franchises/mcu.ts
// MCU — all 38 films in canonical release/watch order.
// Each entry is verified against its primary metadata ID and seeds a deterministic Spün ID at runtime.

import type { FranchiseEntry } from '../types.js';

export const mcu: FranchiseEntry[] = [
  { order: 1, spun_id: "iron-man-681671", title: "Iron Man", primary_id: 1726, relation: 'main',      note: 'Start here — Phase 1' },
  { order: 2, spun_id: "the-incredible-hulk-028101", title: "The Incredible Hulk", primary_id: 1724, relation: 'main',      note: null },
  { order: 3, spun_id: "iron-man-2-599965", title: "Iron Man 2", primary_id: 10138, relation: 'sequel',    note: null },
  { order: 4, spun_id: "thor-541284", title: "Thor", primary_id: 10195, relation: 'main',      note: null },
  { order: 5, spun_id: "captain-america-the-first-avenger-618307", title: "Captain America: The First Avenger", primary_id: 1771, relation: 'main',      note: null },
  { order: 6, spun_id: "the-avengers-532849", title: "The Avengers", primary_id: 24428, relation: 'main',      note: 'Phase 1 finale' },
  { order: 7, spun_id: "iron-man-3-553090", title: "Iron Man 3", primary_id: 68721, relation: 'sequel',    note: 'Phase 2 begins' },
  { order: 8, spun_id: "thor-the-dark-world-242917", title: "Thor: The Dark World", primary_id: 76338, relation: 'sequel',    note: null },
  { order: 9, spun_id: "captain-america-the-winter-soldier-029356", title: "Captain America: The Winter Soldier", primary_id: 100402, relation: 'sequel',    note: null },
  { order: 10, spun_id: "guardians-of-the-galaxy-444145", title: "Guardians of the Galaxy", primary_id: 118340, relation: 'main',      note: null },
  { order: 11, spun_id: "avengers-age-of-ultron-612613", title: "Avengers: Age of Ultron", primary_id: 99861, relation: 'sequel',    note: null },
  { order: 12, spun_id: "ant-man-661507", title: "Ant-Man", primary_id: 102899, relation: 'main',      note: null },
  { order: 13, spun_id: "captain-america-civil-war-249836", title: "Captain America: Civil War", primary_id: 271110, relation: 'sequel',    note: 'Phase 3 begins' },
  { order: 14, spun_id: "doctor-strange-075345", title: "Doctor Strange", primary_id: 284052, relation: 'main',      note: null },
  { order: 15, spun_id: "guardians-of-the-galaxy-vol-2-556752", title: "Guardians of the Galaxy Vol. 2", primary_id: 283995, relation: 'sequel',    note: null },
  { order: 16, spun_id: "spider-man-homecoming-006243", title: "Spider-Man: Homecoming", primary_id: 315635, relation: 'main',      note: null },
  { order: 17, spun_id: "thor-ragnarok-222582", title: "Thor: Ragnarok", primary_id: 284053, relation: 'sequel',    note: null },
  { order: 18, spun_id: "black-panther-561920", title: "Black Panther", primary_id: 284054, relation: 'main',      note: null },
  { order: 19, spun_id: "avengers-infinity-war-599819", title: "Avengers: Infinity War", primary_id: 299536, relation: 'sequel',    note: null },
  { order: 20, spun_id: "ant-man-and-the-wasp-825671", title: "Ant-Man and the Wasp", primary_id: 363088, relation: 'sequel',    note: null },
  { order: 21, spun_id: "captain-marvel-564082", title: "Captain Marvel", primary_id: 299537, relation: 'main',      note: null },
  { order: 22, spun_id: "avengers-endgame-441953", title: "Avengers: Endgame", primary_id: 299534, relation: 'sequel',    note: 'Phase 3 finale' },
  { order: 23, spun_id: "spider-man-far-from-home-285947", title: "Spider-Man: Far From Home", primary_id: 429617, relation: 'sequel',    note: 'Phase 4 begins' },
  { order: 24, spun_id: "black-widow-474040", title: "Black Widow", primary_id: 497698, relation: 'main',      note: null },
  { order: 25, spun_id: "shang-chi-and-the-legend-of-the-ten-rings-491646", title: "Shang-Chi and the Legend of the Ten Rings", primary_id: 566525, relation: 'main', note: null },
  { order: 26, spun_id: "eternals-469505", title: "Eternals", primary_id: 524434, relation: 'main',      note: null },
  { order: 27, spun_id: "spider-man-no-way-home-523845", title: "Spider-Man: No Way Home", primary_id: 634649, relation: 'sequel',    note: null },
  { order: 28, spun_id: "doctor-strange-in-the-multiverse-of-madness-053213", title: "Doctor Strange in the Multiverse of Madness", primary_id: 453395, relation: 'sequel', note: null },
  { order: 29, spun_id: "thor-love-and-thunder-335045", title: "Thor: Love and Thunder", primary_id: 616037, relation: 'sequel',    note: null },
  { order: 30, spun_id: "black-panther-wakanda-forever-788973", title: "Black Panther: Wakanda Forever", primary_id: 505642, relation: 'sequel',    note: 'Phase 4 finale' },
  { order: 31, spun_id: "ant-man-and-the-wasp-quantumania-361367", title: "Ant-Man and the Wasp: Quantumania", primary_id: 640146, relation: 'sequel',    note: 'Phase 5 begins' },
  { order: 32, spun_id: "guardians-of-the-galaxy-vol-3-821632", title: "Guardians of the Galaxy Vol. 3", primary_id: 447365, relation: 'sequel',    note: null },
  { order: 33, spun_id: "the-marvels-433256", title: "The Marvels", primary_id: 609681, relation: 'sequel',    note: null },
  { order: 34, spun_id: "captain-america-brave-new-world-881925", title: "Captain America: Brave New World", primary_id: 822119, relation: 'sequel',    note: 'Phase 5 continues' },
  { order: 35, spun_id: "thunderbolts-092245", title: "Thunderbolts*", primary_id: 986056, relation: 'main',      note: 'Phase 5 finale' },
  { order: 36, spun_id: "the-fantastic-4-first-steps-307443", title: "The Fantastic 4: First Steps", primary_id: 617126, relation: 'main',      note: 'Phase 6 begins' },
  { order: 37, spun_id: "spider-man-brand-new-day-824972", title: "Spider-Man: Brand New Day", primary_id: 969681, relation: 'sequel',    note: 'Last solo film before Doomsday' },
  { order: 38, spun_id: "avengers-doomsday-676854", title: "Avengers: Doomsday", primary_id: 1003596, relation: 'sequel',    note: 'Phase 6 — Avengers finale' },
];
